app/views/components/help_and_support_message.scala.html
app/views/remove/RemoveCheckYourAnswersView.scala.html

[Front-End]
- Wrapped the button with the button-group styling
- Updated spacing on the headline

[MMCA-3527] Adding updates to the remove authority journey

---

app/controllers/ViewAuthorityController.scala
app/controllers/remove/RemoveCheckYourAnswers.scala
app/services/EditSessionService.scala
app/viewmodels/CheckYourAnswersEditHelper.scala
app/viewmodels/CheckYourAnswersRemoveHelper.scala
conf/messages.cy
conf/messages.en
test/controllers/remove/RemoveCheckYourAnswersControllerSpec.scala
test/services/EditSessionServiceSpec.scala

JIRA Link : https://jira.tools.tax.service.gov.uk/browse/MMCA-3526

MMCA-3526 : Further logic for display of business name

---

app/assets/components/_table.scss
app/assets/stylesheets/application.scss
app/views/partials/ManageAuthoritiesTable.scala.html

[MMCA-3541] Fixing table responsive issue

---

app/views/components/inputCheckboxesWithLegend.scala.html
app/views/components/inputRadio.scala.html
app/views/components/inputRadioNoFieldset.scala.html
app/views/components/inputText.scala.html
conf/messages.cy
conf/messages.en

[MMCA-3918] Fixing error identification missing

---

app/views/NoAvailableAccountsView.scala.html

JIRA Link : https://jira.tools.tax.service.gov.uk/browse/MMCA-3963

MMCA-3963 : Non-compliance : Issue#4 - Two h1s

---

conf/messages.cy
conf/messages.en

JIRA Link : https://jira.tools.tax.service.gov.uk/browse/MMCA-4026

MMCA-4026 : Update guidance text

---

app/utils/StringUtils.scala
app/viewmodels/CheckYourAnswersEditHelper.scala
app/viewmodels/CheckYourAnswersHelper.scala
test/utils/StringUtilsSpec.scala
test/viewmodels/CheckYourAnswersEditHelperSpec.scala
test/viewmodels/CheckYourAnswersHelperSpec.scala
test/views/AuthorisedUserViewSpec.scala

Code changes to show (Northern Ireland),  next to Your account in Edit journey

MMCA - 3998 XI & Manage your account authorities - edit journey changes

---

app/controllers/add/AccountsController.scala

JIRA Link : https://jira.tools.tax.service.gov.uk/browse/MMCA-4010

MMCA-4010 : XI & Manage your account authorities - add journey changes

---

conf/messages.cy
conf/messages.en

JIRA Link : https://jira.tools.tax.service.gov.uk/browse/MMCA-4046

MMCA-4046 : Issue: Page title not correct #5627

---

test/models/CustomsAccountsSpec.scala
test/models/EditStateSpec.scala
test/models/InternalIdSpec.scala
test/services/edit/EditAuthorityValidationServiceSpec.scala
test/services/edit/EditCheckYourAnswersValidationServiceSpec.scala
test/utils/DateUtilsSpec.scala
test/utils/StringUtilsSpec.scala

New test classes for InternalId, EditState, EditCheckYourAnswersValidationService, EditAuthorityValidationService and DateUtils have been added. Also additional test cases have been added for CDSAccountStatus

Test Coverage increment misc  - Added tests for improving the unit test coverage

---

test/controllers/add/AuthorisedUserControllerSpec.scala
test/controllers/add/AuthorityEndControllerSpec.scala
test/controllers/add/AuthorityEndDateControllerSpec.scala
test/controllers/edit/EditAuthorityEndControllerSpec.scala
test/controllers/edit/EditAuthorityEndDateControllerSpec.scala
test/forms/AuthorityEndDateFormProviderSpec.scala
test/services/add/AddAuthorityValidationServiceSpec.scala

This PR is solely to improve the Unit test coverage. Below are the things that have been done as part of this PR
New test classes have been added for various missing controllers' test.
New tests have been added in existing AuthorisedUserController
Test class has been added for AuthorityEndDateFormProvider

Coverage Increment Misc_1 Improve Test coverage

---

conf/messages.cy
conf/messages.en

Description - Error msg has been updated by removing the period at the end

[MMCA-4159]  - Remove period from the error msg

---

app/viewmodels/CheckYourAnswersEditHelper.scala
test/viewmodels/CheckYourAnswersEditHelperSpec.scala

This change is only for the Acceptance Criteria 5.

[MMCA-4090-AC-5]  - AC 5 for Maintain consistency for the 'Northern Ireland' label across the CDS Financials pages

---

test/controllers/add/AuthorisedUserControllerSpec.scala
test/controllers/remove/RemoveCheckYourAnswersControllerSpec.scala

Description - Use of common method for application builder and remove warnings

[MMCA-4365] - Address Feedback to customs-manage-authorities-frontend changes made in 4339

---

app/views/add/AddConfirmationView.scala.html
app/views/components/addConfirmationPanel.scala.html
app/views/components/editConfirmPanel.scala.html
app/views/components/removeConfirmPanel.scala.html
test/views/components/AddConfirmationPanelSpec.scala
test/views/components/EditConfirmPanelSpec.scala

[Tasks]
- Updated the order of the text on the confirmation page
- Added unit tests

[MMCA-4666] Audit and change the order of the text on the confirmation

---

app/viewmodels/ManageAuthoritiesTableViewModel.scala
test/controllers/ManageAuthoritiesControllerSpec.scala
test/viewmodels/ManageAuthoritiesTableViewModelSpec.scala

Description - Remove unused view model and parameters from ManageAuthoritiesTableViewModel and associated test

[MMCA-4668] - Remove unused code from 'ManageAuthoritiesTableViewModel' and related tests

---

app/views/components/eori_text.scala.html
test/views/components/EoriTextSpec.scala

[Tasks]
- Changed the `<p>` tag to an `<h2>` tag to fix an accessibility issue
- Updated unit tests to validate the change

[MMCA-5111] Fix the accessibility test finding

---

app/controllers/add/AccountsController.scala
app/controllers/add/AuthorisedUserController.scala
app/controllers/edit/EditCheckYourAnswersController.scala
app/controllers/remove/RemoveCheckYourAnswers.scala
app/models/AuthorisedAccounts.scala
app/services/AuthorisedAccountsService.scala
project/AppDependencies.scala
project/plugins.sbt
test/controllers/AccountsControllerSpec.scala
test/controllers/add/AuthorisedUserControllerSpec.scala
test/controllers/edit/EditCheckYourAnswersControllerSpec.scala
test/controllers/remove/RemoveCheckYourAnswersControllerSpec.scala
test/models/AuthorisedAccountsSpec.scala
test/services/AuthorisedAccountsServiceSpec.scala

MMCA-5208 - Update customs-manage-authorities-frontend for DDA/NI logic

---

test/controllers/add/AuthorisedUserControllerSpec.scala
test/controllers/edit/EditCheckYourAnswersControllerSpec.scala

Description - Fix compilation issues in the tests

[MMCA-5208]  - Fix compilation issues in tests

---

app/controllers/add/AuthorisedUserController.scala
test/controllers/add/AuthorisedUserControllerSpec.scala

MMCA-5208 Ensure XI authorities can be added to EU owned accounts

---

build.sbt
project/AppDependencies.scala
project/plugins.sbt

[Tasks]
- Upgrade library dependencies to the latest versions

[MMCA-5194] Upgraded library versions

---

app/views/templates/Layout.scala.html

[Tasks]
- Temporarily removed the `main.js` script which only contained the browser back functionality

[MMCA-5264] Temporarily removed the main.js script

---

app/views/templates/Layout.scala.html

[Tasks]
- Moved the language toggle above the nav

[MMCA-5253] Move language toggle above Nav

---

conf/application.conf
test/config/FrontendAppConfigSpec.scala

Updated the GOV research banner to new survey link

MMCA-5295: Update GOV survey link

---

app/views/add/EoriNumberView.scala.html
test/controllers/add/EoriNumberControllerSpec.scala

[MMCA-5315] - Update view for populate correct feature fag text

---

app/assets/components/_table.scss

The initial DAC assessment of the CDS Financials service has identified some ares for improvement to align with the government’s WACG 2.1 guidelines. 
This change can be seen in /customs/manage-authorities/manage-account-authorities

MMCA-5363: responsive table implementation adjustments

---

build.sbt
project/AppDependencies.scala
project/plugins.sbt

Description - Update library versions
Below has been done as part of this PR

[MMCA - 5392] - Update library versions
